// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/agent.proto

package proto

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Agent service

func NewAgentEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Agent service

type AgentService interface {
	CreatePod(ctx context.Context, in *Pod, opts ...client.CallOption) (*Pod, error)
}

type agentService struct {
	c    client.Client
	name string
}

func NewAgentService(name string, c client.Client) AgentService {
	return &agentService{
		c:    c,
		name: name,
	}
}

func (c *agentService) CreatePod(ctx context.Context, in *Pod, opts ...client.CallOption) (*Pod, error) {
	req := c.c.NewRequest(c.name, "Agent.CreatePod", in)
	out := new(Pod)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Agent service

type AgentHandler interface {
	CreatePod(context.Context, *Pod, *Pod) error
}

func RegisterAgentHandler(s server.Server, hdlr AgentHandler, opts ...server.HandlerOption) error {
	type agent interface {
		CreatePod(ctx context.Context, in *Pod, out *Pod) error
	}
	type Agent struct {
		agent
	}
	h := &agentHandler{hdlr}
	return s.Handle(s.NewHandler(&Agent{h}, opts...))
}

type agentHandler struct {
	AgentHandler
}

func (h *agentHandler) CreatePod(ctx context.Context, in *Pod, out *Pod) error {
	return h.AgentHandler.CreatePod(ctx, in, out)
}
